### ISSUE TITLE
Addon dont load on new geyser versions

### ISSUE THREAD

**Issue by Rakise** [Camotoy/floodgate-skript#13]
The plugin does not work with the new versions of geyser (the new great update that added the 1.17 in geyser) to be more specific to the version: 1.4.0-Snapshot(1.17.0 bedrock, Java 1.17), It does not detect the floodgate plugin name that is written as Floodgate-Spigot in the new update

**Comment by TheManchineel** [comment]
Can confirm. The plugin is now called Floodgate-Spigot instead of Floodgate-Bukkit

**Comment by Camotoy** [comment]
This project does support the latest Floodgate version under the Floodgate 2.0 branch. Sometime soon I will publish a new release, but for now it is possible to compile to support it.

**Comment by Camotoy** [comment]
Resolved.
