### ISSUE TITLE
Seems like it's not even detected

### ISSUE THREAD

**Issue by Invy55** [Camotoy/floodgate-skript#3]
```
[21:02:07 INFO]: [Skript] Reloading all scripts...
[21:02:07 ERROR]: can't understand this event: 'if player is from floodgate' (join.sk, line 1: if player is from floodgate:')
[21:02:07 INFO]: Loaded 1 script with a total of 0 triggers and 0 commands in 0 seconds
[21:02:07 INFO]: [Skript] Encountered 1 error while reloading all scripts!
```
Please help me

**Comment by Camotoy** [comment]
What version of Skript are you using?

**Comment by Camotoy** [comment]
And do you have Floodgate installed?

**Comment by Invy55** [comment]
> What version of Skript are you using?

I'm using latest Skript version downloaded from SkriptLang/Skript and I've Geyser, floodgate and viaversion installed all working

**Comment by Invy55** [comment]
> And do you have Floodgate installed?

yes of course

**Comment by Camotoy** [comment]
Hi, I'm so sorry for the delay! I just tested and it works on 1.16.2 with the latest beta Skript.

**Comment by Invy55** [comment]
> Hi, I'm so sorry for the delay! I just tested and it works on 1.16.2 with the latest beta Skript.

I'm new to skript can you pls show me a working example?

**Comment by Camotoy** [comment]
Ah, I see your error.

You need to put `on join:` before your first line, so Skript understands when to execute it.

**Comment by Camotoy** [comment]
I'm going to assume this error has been fixed. If not, let me know!

**Comment by Invy55** [comment]
> I'm going to assume this error has been fixed. If not, let me know!

yes I just don't use so its fixed
