### ISSUE TITLE
UUID Breaks Skript

### ISSUE THREAD

**Issue by ShaneBeee** [Camotoy/floodgate-skript#4]
Hello, heads up:
https://github.com/DoctorMacc/floodgate-skript/blob/1dce53e74e717f336a8ffbbaba30fc54da6dddd8/src/main/java/org/geysermc/floodgateskript/expressions/GetFloodgateUUID.java#L22-L25

Due to the fact that "floodgate" is optional, this actually overrides Skript's uuid expression, and breaks all uuids for regular players. This is very detrimental to Skript, as people use uuids for a lot of variables.

Example code:
```vb
command /players:
	trigger:
		send "&dPlayers &7(&b%size of all players%&7):"
		loop all players:
			send "&bPlayer: &7%name of loop-player% :: &aUUID: &7%uuid of loop-player%"
```

output:
```
[04:11:13 INFO]: Players (2):
[04:11:13 INFO]: Player: ShaneBee :: UUID: <none>
[04:11:13 INFO]: Player: *ShaneBee7386 :: UUID: 00000000-0000-0000-0009-01fa7a560a0a
```

As you can see, "ShaneBee" (my java account) is showing a uuid of none. 

I recommend making the "floodgate" part of the syntax non optional, ie:
```vb
"[the] uuid of [the] floodgate %player%"
```

Another note, Skript's basic uuid expression already returns this same uuid (at least it did for me, after adding this add-on I got the same uuid value) for example, using the same code as above, but without this add-on:
```
[04:17:54 INFO]: Players (2):
[04:17:54 INFO]: Player: ShaneBee :: UUID: 1748129a-525b-44eb-8fb5-8953d0287507
[04:17:54 INFO]: Player: *ShaneBee7386 :: UUID: 00000000-0000-0000-0009-01fa7a560a0a
```

**Comment by Camotoy** [comment]
Thanks for the information! Yeah, I don't see why this needs to be a thing, then, so I'll likely remove it soon. Thanks!

**Comment by Camotoy** [comment]
Addressed in the latest commit/release. Thanks for reaching out!

**Comment by ShaneBeee** [comment]
You're welcome. And thank you for taking care of it so quickly 👍
